name: Main

on:
  push:
    branches: [ master ]
    tags:
      - '*'

jobs:

  build_docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9]

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: false

      - name: Install OS dependencies
        run: |
          sudo apt-get install doxygen

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Python dependencies
        run: |
          pip install sphinx sphinx-rtd-theme breathe

      - name: Setup Envvars
        run: |
            if [[ $GITHUB_REF = "refs/tags/"* ]] ; then echo "OSQP_VERSION=${GITHUB_REF/refs\/tags\//}" ; else echo "OSQP_VERSION=0.0.0" ; fi >> $GITHUB_ENV
            if [[ $GITHUB_REF = "refs/tags/"* ]] ; then echo "OSQP_NAME=osqp-${GITHUB_REF/refs\/tags\//}-${{ runner.os }}" ; else echo "OSQP_NAME=osqp-0.0.0-${{ runner.os }}" ; fi >> $GITHUB_ENV

      - name: Build docs
        run: |
          cd docs && make HTMLCOPYDIR=../site/docs html && touch ../site/docs/.nojekyll

      - name: Update gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ".github/workflows/build_docs.sh"
        shell: bash
